export class Traduction {
    public static fr = {
      date_activation: "Date d'activation",
      limitation: "La période entre la date de début et la date de fin est limitée à 3 mois",
      rafraichissement2: "ATTENTION : un rafraichissement de la base est en cours. Veuillez reporter votre action.",
      assets_report: "Rapport des assets",
      nombre_de_droits_associes: "Nombre de droits associés",
      count: "Nombre de droits",
      desc_fr: "Description FR",
      desc_en: "Description EN",
      proprietaire: "Propriétaire",
      cellule_locale_gestionnaire: "cellule locale gestionnaire",
      referentiel_app: "Referentiel applicatif",
      identifiant_ref_app: "Identifiant dans le referentiel applicatif",
      date_avancement_list: "Date de la campagne de la certification",
      nom_compagne_avancement_list: "Nom de la campagne de certification",
      pole_avancement_list: "Pôle des utilisateurs ayant les droits",
      etiquette_avancement: "Étiquettes de lignes",
      total_avancement: "Total",
      traite_avancement: "Traité",
      a_traite_avancement: "À traité",
      certifie_avancement: "certification",
      participation_avancement: "participation",
      select: "Sélectionner tout",
      unselect: "Supprimer la sélection",
  
      eid: "UID",
      display_name: "Nom",
      display_uo: "UO",
      count_: "Nombre d'habilitations",
      no_user: "ACTUELLEMENT AUCUN UTILISATEUR NE DISPOSE DE + DE 300 DROITS",
      users: "UTILISATEURS AYANT PLUS DE 300 HABILITATIONS",
      title: "UTILISATEURS AYANT PLUS DE 300 HABILITATIONS",
      liste: "Afficher la liste",
      list_key: "Liste des droits",
      prenom: "Prénom",
      nom: "Nom",
  
      uo_list: "List des uo",
    
    etat_avancement_des_certifications: "État d’avancement des certifications",
    pole_avancement: "POLE DES UTILISATEURS DE LA CELLULE LOCALE",
    droits_avancement: "DROITS DE LA CELLULE LOCALE",
    pole_avancement_desc: "vous permet de générer l’état d’avancement de la certification des utilisateurs appartenant à votre pôle",
    droits_avancement_desc: "vous permet de générer l’état d’avancement de la certification sur les droits géré par la cellule locale",
    user_pole: "Pôle des utilisateurs de la cellule locale",
    user_droits: "Droits de la cellule locale",

    janvier: "janvier",
    fevrier: "février",
    mars: "mars",
    avril: "avril",
    mai: "mai",
    juin: "juin",
    juillet: "juillet",
    aout: "août",
    septembre: "septembre",
    octobre: "octobre",
    novembre: "novembre",
    decembre: "décembre",

    tab_his: "Tableau d’historisation",
    statistique_inst: "Rapport généré",
    statistiques_his: "Historique des statistiques",
    table_instancee: "Générer un rapport",
    statistiques: "Rapport des statistiques",

    nb_droits_sd: "Nombre total de droits sans distinction",
    nb_equipes: "Nombre total d’équipes",
    nb_droits: "Nombre total de droits",
    nb_sod: "Nombre total de SOD",
    nb_profil_metier: "Nombre total de profils métiers",
    nb_droits_sans_pv: "Nombre total de droits sans périmètre de visibilité",
    nb_droits_avec_pv: "Nombre total de droits avec périmètre de visibilité",
    nb_applications: "Nombre total d’applications",
    nb_habilitations: "Nombre total d’habilitations",
    nb_droits_sh: "Nombre total de droits sans habilitation",
    nb_utilisateurs: "Nombre total d’utilisateurs",
    nb_utilisateurs_a: "Nombre total d’utilisateurs actifs",
    nb_utilisateurs_non_a: "Nombre total d’utilisateurs inactifs",
    nb_utilisateurs_avec_min_un: "Nombre total d’utilisateurs avec au moins 1 droit",
    date_generation: "Date de génération",

    show: "Afficher",
    elements: "éléments",
    home: "Accueil",
    slogan: "La banque d’un monde qui change",
    roles_catalog: "Catalogue des droits",
entitlement_requests: "Demandes d'habilitation",
identities: "Identités",
entitlements: "Habilitations",
external_certification: "Certification hors MyAccess",
roles_extraction: "Extraction des droits",
reset_filters: "Effacer les filtres",
set_filters: "Appliquer les filtres",
code_unique: "code unique",
libelle_asset: "Libellé de l'asset",
code_asset: "code asset",
actif_api: "Actif API",
actif_ui: "Actif UI",
cellule_locale_gestionnaire_id: "cellule locale gestionnaire ID",
cellule_locale_gestionnaire_nom: "Cellule locale gestionnaire nom",
criticite: "Criticité",
date_fin_obligatoire: "Date de fin obligatoire",
description_en: "Description EN",
description_fr: "Description FR",
duree_habilitation: "Durée habilitation",
email: "Email",
implementeurs_id: "Implementeurs ID",
implementeurs_nom: "Implementeurs nom",
justificatif_obligatoire: "Justificatif obligatoire",
libelle: "Libellé",
metier: "Métier",
perimetre_exclusion: "Perimetre d'exclusion",
perimetre_execution: "Perimetre d'execution",
perimetre_visibilite: "perimetre de visibilité",
proprietaire_id: "Propriétaire ID",
proprietaire_nom: "propriétaire nom",
statut: "Statut",
type: "Type",
type_equipe: "Type équipe",
type_provisioning: "Type d’implémentation",
valideur_1_id: "Valideur 1 ID",
valideur_1_nom: "valideur 1 nom",
valideur_1_type: "valideur 1 type",
valideur_2_id: "Valideur 2 ID",
valideur_2_nom: "valideur 2 nom",
valideur_2_type: "valideur 2 type",
valideur_3_id: "Valideur 3 ID",
valideur_3_nom: "valideur 3 nom",
valideur_3_type: "Valideur 3 type",
valideur_4_id: "Valideur 4 ID",
valideur_4_nom: "Valideur 4 nom",
valideur_4_type: "Valideur 4 type",
valideur_retrait_type: "Valideur retrait type",
role: "Droit",
business_profil: "Profil métier",
team_members: "Membres de l’équipe",
role_life_cycle: "Cycle de vie du droit",
members_identity: "Identités de membres",
attribute: "Attribut",
current_value: "Valeur actuelle",
change: "Modification",
creation_date: "Date de création",
deletion_date: "Date de suppression",
liste_droits: "Liste des droits",
requests_report: "Rapport de demandes",
start_date: "Date de début",
end_date: "Date de fin",
generate: "Générer",
owners: "Propriétaire",
validateur: "Valideur",
security_team: "Équipe sécurité",
imp_team: "Équipe implémenteur",
manager: "Manager",
local_cell: "Cellule locale",
local_cell2: "Cellule locale (sur une période de 2 mois maximum)",
central_cell: "Cellule centrale",
central_cell2: "Cellule centrale (sur une période de 2 mois maximum)",
no_element: "Aucun élément",
invalid_dates_options: "La période maximale entre la date de début et la date de fin n’a pas été respectée.",
action: "Action",
asset: "Application",
asset_id: "Application ID",
beneficiaire: "Bénéficiaire",
commentaire: "Commentaire",
date_decision_implementeur: "Date décision implémenteur",
date_decision_implementeur_bis: "Date décision implémenteur bis",
date_decision_valideur_1: "Date decision valideur 1",
date_decision_valideur_2: "Date decision valideur 2",
date_decision_valideur_3: "Date decision valideur 3",
date_decision_valideur_4: "Date decision valideur 4",
date_fin: "Date de fin",
date_fin_habilitation: "Date de de fin habilitation",
date_soumission: "Date soumission",
date_soumission_implementeur: "Date soumission implémenteur",
date_soumission_implementeur_bis_legacy: "Date soumission implémenteur bis",
date_soumission_valideur_1: "Date soumission valideur 1",
date_soumission_valideur_2: "Date soumission valideur 2",
date_soumission_valideur_3: "Date soumission valideur 3",
date_soumission_valideur_4: "Date soumission valideur 4",
demandeur: "Demandeur",
equipe_implementeur: "équipe implémenteur",
id: "ID",
implementeur: "Implémenteur",
implementeur_bis_legacy: "Implémenteur bis",
libelle_droits: "Libellé du droit",
perimetre_01: "Périmètre 01",
perimetre_02: "Périmètre 02",
perimetre_03: "Périmètre 03",
perimetre_04: "Périmètre 04",
perimetre_05: "Périmètre 05",
perimetre_06: "Périmètre 06",
perimetre_07: "Périmètre 07",
perimetre_08: "Périmètre 08",
perimetre_09: "Périmètre 09",
perimetre_10: "Périmètre 10",
request_id: "ID demande",
right_id: "ID droit",
roles_list_of_profil: "Liste des droits PW",
type_droit: "Type droit",
valideur_1: "Valideur 1",
valideur_2: "Valideur 2",
valideur_3: "Valideur 3",
valideur_4: "Valideur 4",
roles_kpi: "KPI des droits",
see_requests_kpi: "Voir les KPI des demandes",
roles_count_by_month: "Nombre de droits par mois",
total_roles_count: "Nombre de droits total actuel",
all_metier: "Tous les métiers",
roles_count: "Nombre de droits",
roles_count_by_metier: "Nombre de droits par métier",
changes_count_by_month: "Nombre de changements par mois",
changes_count_by_metier: "Nombre de changements par métier",
created: "Création",
modified: "Modification",
deleted: "Suppression",
month: "Mois",
all_twelve_months: "Tous les 13 derniers mois glissants",
consult: "Consulter",
close: "Fermer",
new_requests_count: "Nombre de nouvelles demandes",
requests_kpi: "KPI des demandes",
see_roles_kpi: "Voir les KPI des droits",
top_ten_requests: "Les 10 droits les plus demandés",
total_requests_count: "Nombre total de demandes d'habilitation",
requests_count_by_metier: "Nombre de demandes par métier",
requests_count: "Nombre de demandes",
new_requests_by_metier: "Nouvelles demandes par métier",
new_requests_by_month: "Nouvelles demandes par mois",
identity: "Identité",
identity_search: "Recherche d’identité",
search: "Rechercher",
valid_uid_date: "Veuillez entrez un UID et une date valide",
uid_scope_diff: "L'UID renseigné n'existe pas ou n'est pas dans votre périmètre",
history: "Historique",
life_cycle: "Cycle de vie",
request_date: "Date demande",
validation_date: "Date validation",
event: "Évènement",
mobility_date: "Date mobilité",
abstract: "Résumé",
select_dispo_options: "Veuillez sélectionner une option disponible",
entitlements_report: "Rapport d’habilitations",
statut_droit: "Statut droit",
sensibilite: "Sensibilité",
etat_utilisateur: "État utilisateur",
pole: "Pôle",
uo: "UO",
code_uo: "Code UO",
uid: "UID",
roles_extract: "Extraction des droits",
roles_report: "Rapport des droits",
libelle_metier: "Libellé métier",
code_iam: "Code AP",
certif: "Certification",
rapport: "Rapport",
avancement: "Avancement",
bilan: "bilan",
etape: "Étape",
etape1_annee_certif: "Année de certification (1 seul choix - OBLIGATOIRE)",
suivant: "suivant",
choix_année: "Choisir une année (obligatoire)",
camp_certif: "Campagne de certification",
lib_drt: "Libellé du droit",
generer: "Générer",
generer_rapport: "Générer un nouveau rapport",
uo_benef: "UO du bénéficiaire",
benef: "Bénéficiaire",
pole_benef: "Pôle du bénéficiaire",
metier_benef: "Métier du bénéficiaire",
libelle2: "Libellé",
nom_campagne: "Nom de la campagne de certification",
status_certif: "Status de la certification",
description2: "Description",
certificateur: "Certificateur",
nom_certificateur: "Nom du certificateur",
description_certif: "Description de la certification",
decision: "Décision",
date_decision: "Date de la décision",
com_certificateur: "Commentaires du certificateur",
com_certificateur2: "Commentaires du certificateur 2",
certif_reassignee_a: "Certification réassignée à : ",
certif_reassignee_le: "Certification réassignée le : ",
filtre_pole : "Filtrage réalisé sur les pôles",
filtre_gestionnaire_du_droit : "Filtre en fonction des droits où la cellule locale est gestionnaire du droit",
uo_du_beneficiaire: "UO du bénéficiaire",
pole_du_beneficiaire: "Pôle du bénéficiaire",
metier_du_beneficiaire: "Métier du bénéficiaire",
nom_de_la_campagne_de_certification: "Nom de la campagne de certification",
statut_de_la_certification: "Statut de la certification",
description_: "Description",
nom_du_certificateur: "Nom du certificateur",
description_de_la_certification: "Description de la certification",
date_de_la_decision: "Date de la décision",
certification_reassignee_a: "Certification réassignée à",
certification_reassignee_le: "Certification réassignée le",
date_de_creation: "Date de création",
select_annee: "Sélectionner une année",
retour_page_precedente: "Retour à la page précédente",
typologie_de_l_habilitation_revue: "typologie de l'habilitation revue",
libelle_de_l_asset: "Libellé de l'asset",
libelle_du_role: "Libellé du rôle",
description_du_droit: "Description du droit",
destinataire_de_la_certification: "Destinataire de la certification",
recertificateur: "Recertificateur",
commentaires_du_recertificateur: "Commentaires du recertificateur",
derniere_reassignation_par: "Dernière réassignation par",
reassign_le: "Dernière reassignation le",
dernier_transfert_le: "Dernier transfert le",
dernier_transfert_par: "Dernier transfert par",
date_de_creation_annee: "Année de création",
bnpp_equipe: "Équipe",
bnp_tit: "Droit",
businessProfil: "Profil métier",
pole_principal: "Type de rapport : pôle du bénéficiaire",
cl_gest_drt: "Type de rapport : Cellule locale Gestionnaire du droit",
typeRapport: "Type de rapport",
generateReportWays: "Deux possibilités vous sont offertes pour générer votre rapport :",
polePrincipal: "Pôle du bénéficiaire",
poleGenerate: "Vous permet de générer le rapport de certification des utilisateurs appartenant à votre pôle.",
celluleLocal: "Cellule locale Gestionnaire de droit",
celluleGenerate: "Vous permet de générer le rapport de certification sur les droits gérés par la cellule locale et ce quelque soit le bénéficiaire.",
filtresRapports: "Filtres appliqués à votre rapport",
filtreCellLocs: "Filtre sur les droits où la cellule locale",
AnneeCertif: "Année de certification",
NotAllowed: "Vous n’êtes pas habilité à accéder à cette section",
pole2: "pôle",
gestionnaire: "est gestionnaire",
camp_certif2: "Campagne de certification",
code_unique_role: "Code unique du rôle",
description_du_role: "Description du rôle",
ttes_les_demandes: "Toutes les demandes (sur une période de 2 mois maximum)",
ttes_les_habil: "Toutes les habilitations",
dateCampagne: "Date de la campagne de certification",
nomCampagne: "Nom de la campagne de certification",
nomCL: "Nom de la cellule locale",
bilanDroits: "Bilan de la campagne de re-certification",
droits: "droits",
achevement: "Achevement",
infoPersonnes: "Informations sur les personnes",
certifies: "Bénéficiaires",
certificateurs: "certificateurs",
infoRessources: "Informations sur les ressources",
assets: "Assets",
droit: "Droits",
globalResults: "Résultats globaux",
participation: "participation",
habilitationsCertifiees: "Habilitations certifiées",
habilitationsApprouvees: "Habilitations approuvées",
habilitationsRejetees: "Habilitations rejetées",
habilitationsNonRevues: "Habilitations non-revues",
participationPP: "participation par pôle",
habilitationsRevuesPP: "Habilitations revues par pôle",
statisticsPerWeek: "Statistique % par semaine",
achevementParCL: "Achèvement par cellule locale",
week: "Semaine",
code_ap: "Code AP",
code_unique_pm_du_droit: "Code du PM associé au droit",
libelle_pm_du_droit: "Libelle du PM associé au droit",
liste_droit_pm: "liste des droits appartenant au PM",
polebilan: "de tous les pôles (cellule déploiement/centrale)",
tasks: "tâches d'implémentation",
tasks_report: "Rapport de tâches",
description: "Description",
priorite: "Priorité",
date_de_signature: "Date de signature",
id_tache: "ID de la tâche",
date_action_implementeur: "Date action implémenteur",
perimetre: "périmètre d'exécution",
report_perimeter: "Rapport des périmètres d'exécution",
multichoix: "choix multiple",
obligatoire: "Obligatoire",
valeurs_possibles: "Valeurs possibles",
type_perimetre: "Type de périmètre",
nombre_de_membres_associes: "Nombre de membres associés",
droits_contenus_dans_profil_metier: "Droits Contenus dans le Profil Métier",
code_de_l_appli: "Code de l'appli",
code_du_droit: "Code du droit",
responsable_de_l_uo: "Responsable de l'UO",
nombre_de_membres: "Nombre de membres",
statut_utilisateur: "Statut de l'utilisateur",
sensibilite_du_droit: "Sensibilité du droit",
convergence_rec: "Convergence recertification CIB ITG",
convergence_application: "Rapport des assets",
convergence_application_entitlements: "Rapport des droits",
convergence_user_entitlements: "Rapport des habilitations - convergence",
convergence_user_entitlements_name: "Habilitations (convergence)",
convergence_user_and_manager: "Rapport des utilisateurs",
inaccessible: "Vous n’êtes pas autorisés à accéder à cette section.",
ApplicatioName: "ApplicationName",
ApplicationDescription: "ApplicationDescription",
ApplicationOwnerUID: "ApplicationOwnerUID",
ApplicationName: "ApplicationName",
EntitlementName: "EntitlementName",
EntitlementValue: "EntitlementValue",
EntitlementDisplayName: "EntitlementDisplayName",
EntitlementDescription: "EntitlementDescription",
ResourceName: "ResourceName",
Username: "Username",
UserDisplayName: "UserDisplayName",
UID: "UID",
AccountName: "AccountName",
Instance: "Instance",
EntitlementType: "EntitlementType",
username: "username",
userdisplayname: "userdisplayname",
firstname: "firstname",
lastname: "lastname",
usermanageruid: "usermanageruid",
Firstname: "Firstname",
Lastname: "Lastname",
Email: "Email",
ecartmyaccess: "Ecart MyAccess - Base Habi",
manque_basehabi: "Droits manquants côté BaseHabi",
manque_myaccess: "Droits manquants côté MyAccess",
date_trait: "Date de traitement",
rapp_ecart: "Rapport des écarts entre MyAccess et BaseHabi",
users_ecart_myac_basehabi: "(réservé aux utilisateurs faisant parti de SEC09 et appartenant à la cellule centrale de MyAccess)",
filtreSOD: "SOD dont est propriétaire la cellule",
libelle_politique_sod: "Libelle de la politique SOD",
libelle_regle: "Libelle de la règle",
gestionnaire_politique_sod: "Gestionnaire de la politique SOD",
description_regle: "Description de la règle",
groupe_1_code_unique: "Groupe 1 code unique",
groupe_1_libelle_droit: "Groupe 1 libelle du droit",
groupe_2_code_unique: "Groupe 2 code unique",
groupe_2_libelle_droit: "Groupe 2 libelle du droit",
proprietaire_regle: "Propriétaire de la règle",
groupsod: "Le(s) droit(s) suivant(s) ...",
groups2sod: "... sont en conflits avec l'un ou plusieurs de ces droits",
btnshowmore: "Afficher plus",
policy: "Politique",
rule: "Règle",
soddetail: "Détails de la SOD",
num1grpcodeunique: "Nombre de droits appartenant au groupe 1",
num2grpcodeunique: "Nombre de droits appartenant au groupe 2",
id_rule: "ID de la règle SOD",
sod_count_by_metier: "Nombre de SOD par métier",
display_kpisod: "Afficher les KPI des SOD",
total_sod_count: "Nombre total de règles SOD",
closedisplay_kpisod: "Masquer les KPI des SOD",

beneficiary_uid: "UID du bénéficiaire",
beneficiary_display_name: "Display name du bénéficiaire",
beneficiary_firstname: "Prénom du bénéficiaire",
beneficiary_lastname: "Nom du bénéficiaire",
beneficiary_email: "Email du bénéficiaire",
unit_manager_uid: "UID du responsable d'UO",
unit_manager_display_name: "Display name du responsable d'UO",
unit_manager_firstname: "Prénom du responsable d'UO",
unit_manager_lastname: "Nom du responsable d'UO",
unit_manager_email: "Email du responsable d'UO",
certifier_uid: "UID du certificateur",
certifier_display_name: "Display name du certificateur",
certifier_firstname: "Prénom du certificateur",
certifier_lastname: "Nom du certificateur",
certifier_email: "Email du certificateur",
right_display_name: "Display name du droit",
source: "Source",
all_perimeters: "Tous les périmètres",
exclusion_pm: "Exclusion des PM",
code_iso: "Code ISO",
code_iso_beneficiary: "Code ISO du bénéficiaire"

    }
// Début du bloc en anglais
public static en = {
date_activation: "Date of activation",
limitation: "The period between the start and end dates is limited to 3 months",
rafraichissement2: "WARNING: A base refit is underway. Please postpone your action.",
assets_report: "Assets report",
count: "Rights count",
desc_fr: "Description FR",
desc_en: "Description EN",
propriétaire: "Owner",
cellule_locale_gestionnaire: "Local cell",
referentiel_app: "Application ref",
identifiant_ref_app: "Application ref ID",
date_avancement_list: "Date of certification campaign",
nom_compagne_avancement_list: "Name of certification campaign",
pole_avancement_list: "Pole of Beneficiary",
etiquette_avancement: "Line labels",
total_avancement: "Total",
traite_avancement: "Processed",
a_traite_avancement: "Processing",
certifie_avancement: "certification",
participation_avancement: "participation",
select: "Select all",
unselect: "Unselect all",

eid: "UID",
display_name: "Name",
display_uo: "UO",
count_: "Number of rights",
no_user: "CURRENTLY NO USER HAS MORE THAN 300 RIGHTS",
users: "USERS WITH MORE THAN 300 RIGHTS",
title: "USERS WITH MORE THAN 300 RIGHTS",
liste: "Display list",
list_key: "List of rights",
prenom: "Name",
nom: "Last Name",

uo_list: "List des uo",

etat_avancement_des_certifications : "Progress status of certification",
pole_avancement : "LOCAL CELL USERS POLE",
droits_avancement : "RIGHTS OF THE LOCAL CELL",
pole_avancement_desc: "Allows you to generate the progress of the certification of the users belonging to your pole",
droits_avancement_desc: "Allows you to generate the progress of the certification on the rights managed by the local cell and",
user_pole : "Pole of the users of the local cell",
user_droits: "Rights of the local cell",
janvier: "January",
fevrier: "February",
mars: "Mars",
avril: "April",
mai: "May",
juin: "Juny",
juillet: "July",
aout: "August",
septembre: "September",
octobre: "October",
novembre: "November",
decembre: "December",

tab_his : "Historisation table",
statistique_inst : "Generated report",
statistiques_his : "Statistics history",
table_instantanee : "Instant report",
statistiques : "Statistic report",

nb_droits_sd: "number of rights without distinction",
nb_equipes: "number of teams",
nb_droits: "number of rights",
nb_sod: "number of SOD",
nb_profil_metier: "number of Business Role",
nb_droits_sans_pv: "number of right without visibility perimeter",
nb_droits_avec_pv: "number of right with visibility perimeter",
nb_applications: "number of applications",
nb_habilitations: "number of entitlements",
nb_droits_sh: "number of rights without entitlements",
nb_utilisateurs: "number of users",
nb_utilisateurs_a: "number of actif users",
nb_utilisateurs_non_a: "number of inactif users",
nb_utilisateurs_avec_min_un: "number of users with minimum one right",

date_generation : "generation date",
show: "Show",
elements: "elements",
slogan: "The bank for a changing world",
home: "Home",

roles_catalog: "Roles catalog",
entitlement_requests: "Access requests",
identities: "Identities",
entitlements: "Access",
external_certification: "Certification outside MyAccess",
roles_extraction: "Roles extraction",
reset_filters: "Reset filters",
set_filters: "Apply filter",
code_unique: "Uniq code",
libelle_asset: "Application name",
code_asset: "Application code",
actif_api: "Enable API",
actif_ui: "Enable UI",
cellule_locale_gestionnaire_id: "Local management unit ID",
cellule_locale_gestionnaire_nom: "Local management unit nom",
criticite: "Criticality",
date_fin_obligatoire: "Mandatory end date",
description_en: "Description EN",
description_fr: "Description FR",
duree_habilitation: "Authorisation duration",
email: "Email",
implementateurs_id: "Implementers ID",
implementateurs_nom: "Implementers name",
justificatif_obligatoire: "Mandatory credential",
libelle: "Name",
metier: "Business",
perimetre_exclusion: "Exclusion perimeter",
perimetre_execution: "Perimeter of execution",
perimetre_visibilite: "Visibility perimeter",
proprietaire_id: "Owner ID",
proprietaire_nom: "Owner name",
statut: "Status",
type: "Type",
type_equipe: "Team type",
type_provisioning: "Type of implementation",
valideur_1_id: "Validator 1 ID",
valideur_1_nom: "Validator 1 name",
valideur_1_type: "Validator 1 type",
valideur_2_id: "Validator 2 ID",
valideur_2_nom: "Validator 2 name",
valideur_2_type: "Validator 2 type",
valideur_3_id: "Validator 3 ID",
valideur_3_nom: "Validator 3 name",
valideur_3_type: "Validator 3 type",
valideur_4_id: "Validator 4 ID",
valideur_4_nom: "Validator 4 name",
valideur_4_type: "Validator 4 type",
valideur_retrait_type: "Validator withdrawal type",
role: "Role",
business_profil: "Business profil",
team_members: "Team members",
role_life_cycle: "Role life cycle",
members_identity: "Identity of members",
attribut: "Attribute",
current_value: "Current value",
change: "Change",
date_creation: "Creation date",
deletion_date: "Deletion date",
liste_droits: "Liste des droits",
requests_report: "Requests report",
start_date: "Start date",
end_date: "End date",
generate: "Generate",
owner: "Owner",
validator: "Validator",
security_team: "Security team",
imp_team: "Provisioning team",
manager: "Manager",
local_cell: "Local cell",
local_cell2: "Local cell (sur une période de 2 mois maximum)",
central_cell: "Central cell",
central_cell2: "Central cell (over a maximum period of 2 months)",
no_element: "No element",
invalid_dates_options: "The maximum period between the start and end dates was not met.",
action: "Action",
asset: "Application",
asset_id: "Application ID",
beneficiaire: "Beneficiary",
commentaire: "Commentary",

date_decision_implementeur: 'Implementation decision date',
date_decision_implementeur_bis_legacy: 'Implementation decision date bis',
date_decision_valideur_1: 'Date decision validator 1',
date_decision_valideur_2: 'Date decision validator 2',
date_decision_valideur_3: 'Date decision validator 3',
date_decision_valideur_4: 'Date decision validator 4',
date_fin: 'end date',
date_fin_habilitation: 'Date of end of authorisation',
date_soumission: 'Submission date',
date_soumission_implementeur: 'Implementation submission date',
date_soumission_implementeur_bis_legacy: 'Date of submission of implementation bis',
date_soumission_valideur_1: 'Date of submission validator 1',
date_soumission_valideur_2: 'Date of submission validator 2',
date_soumission_valideur_3: 'Date of submission validator 3',
date_soumission_valideur_4: 'Date of submission validator 4',
demandeur: 'Applicant',
equipe_implementeur: 'Implementation team',
id: 'ID',
implementeur: 'Implementer',
implementreur_bis_legacy: 'Bis implementer',
libelle_droit: 'Role name',
perimetre_01: 'Perimeter 01',
perimetre_02: 'Perimeter 02',
perimetre_03: 'Perimeter 03',
perimetre_04: 'Perimeter 04',
perimetre_05: 'Perimeter 05',
perimetre_06: 'Perimeter 06',
perimetre_07: 'Perimeter 07',
perimetre_08: 'Perimeter 08',
perimetre_09: 'Perimeter 09',
perimetre_10: 'Perimeter 10',
request_id: 'Request ID',
right_id: 'Right ID',
roles_list_of_profil: 'Roles list of business profil',
type_droit: 'Role type',
valideur_1: 'Validator 1',
valideur_2: 'Validator 2',
valideur_3: 'Validator 3',
valideur_4: 'Validator 4',
roles_kpi: 'Roles KPI',
see_requests_kpi: 'See requests KPI',
roles_count_by_month: 'Roles count by month',
total_roles_count: 'Total roles count',
all_metier: 'All professions',
roles_count: 'Roles count',
roles_count_by_metier: 'Roles count by profession',
changes_count_by_month: 'Changes count by month',
changes_count_by_metier: 'Changes count by profession',
created: 'Created',
modified: 'Modified',
deleted: 'Deleted',
month: 'Month',
all_twelve_months: 'Every last 13 rolling months',
consult: 'Consult',
close: 'Close',
new_requests_count: 'New requests count',
requests_kpi: "Requests KPI",
see_roles_kpi: "See roles KPI",
top_ten_requests: "Top 10 requested roles",
total_requests_count: "Requests count",
requests_count_by_metier: "Requests by profession",
requests_count: "Requests count",
new_requests_by_metier: "New requests by profession",
new_requests_by_month: "New requests by month",
identity: "Identity",
identity_search: "Search an identity",
search: "Search",
valid_uid_date: "Please select an valid UID and date",
uid_scope_diff: "The UID entered does not exist or is not within your scope",
history: "History",
life_cycle: "Life cycle",
request_date: "Request date",
validation_date: "Validation date",
event: "Event",
mobility_date: "Mobility date",
abstract: "Abstract",
select_dispo_options: "Please select a valid option",
entitlements_report: "Access report",
statut_droits: "Role status",
sensibilite: "Sensibility",
etat_utilisateur: "User state",
pole: "Pole",
uo: "UO",
code_uo: "UO code",
uid: "UID",

roles_extract: "Roles extract",
roles_report: "Roles report",
libelle_metier: "Business name",
code_iam: "AP code",
certif: "Certification",
rapport: "Report",
avancement: "Advancement",
bilan: "assessment",
etape: "Stage",
etape1_annee_certif: "Year of certification (only 1 choice - MANDATORY)",
suivant: "Next",
choix_année: "Select a year (mandatory)",
camp_certif: "Certification campaign",
lib_drt: "Legal description",
pole_benef: "Pole of the beneficiary",
generer: "Generate",
generer_rapport: "Generating a new report",
uo_benef: "Beneficiary's UO",
benef: "Beneficiary",
metier_benef: "Beneficiary's Business",
libelle2: "Wording",
nom_campagne: "Name of certification campaign",
status_certif: "Status of certification",
description2: "Description",
certificateur: "Certifier",
nom_certificateur: "Name of certifier",
description_certif: "Description of the certification",
decision: "Decision",
date_decision: "Date of decision",
com_certificateur: "Comments of the certifier",
com_certificateur2: "Comments of the certifier 2",
certif_reassignee_a: "Certification reassigned to :",
certif_reassignee_le: "Re-assigned Certification :",
filtre_pole : "Filtering on the poles",
filtre_Gestionnaire_du_droit : "Filter according to rights where the local cell is the law manager",
uo_du_beneficiaire: "Beneficiary UO",
pole_du_beneficiaire: "Pole of the beneficiary",
metier_du_beneficiaire: "Beneficiary's Business",
nom_de_la_campagne_de_certification: "Name of certification campaign",
statut_de_la_certification: "Status of Certification",
description_ : "Description",
nom_du_certificateur: "Name of certifier",
description_de_la_certification: "Description of the certification",
date_de_la_decision: "Date of decision",
certification_reassignee_a: "Re-assigned Certification",
certification_reassignee_le: "Reassigned Certification",
date_de_creation: "Inception date",
selec_une_annee: "Select one year",
retour_page_prec: "Return to previous page",
typologie_de_l_habilitation_revue: "Typology of empowerment reviewed",
libelle_de_l_asset: "Label of the asset",
libelle_du_role: "Role label",
code_unique_role: "Unique role code",
description_du_role: "Role description",
description_du_droit: "Role description",
destinataire_de_la_certification: "Addressee of certification",
recertificateur: "Author",
commentaires_du_recertificateur: "Comments of the recertification",
reassignment_par: "Last reassignment by",
reassign_le: "Last reassignment",
dernier_transfert_le: "Last transfer",
dernier_transfert_par: "Final transfer by",
date_de_creation_annee: "Year of creation",
bnpp_equipe: "Team",
it: "Right",
business: "Business profile",
pole_principal: "Report type: Pole of the beneficiary",
cl_gest_drt: "Type of report: Local unit Law manager",
typeRapport: "Type of report",
generateReportWays: "Two options are available to you to generate your report :",
polePrincipal: "Pole of the beneficiary",
poleGenerate: "allows you to generate the certification report of users belonging to your pole.",
celluleLocal: "local cell Law manager",
cellGenerate: "allows you to generate the certification report on rights managed by the local cell, regardless of the beneficiary.",
filtreRapport: "Filters applied to your report",
filtreCellLoc: "Filter on rights where the local cell",
AnneeCertif: "Year of certification",
NotAllowed: "You are not entitled to access this section",
pole2: "Pole :",
gestionnaire: "is manager",
camp_certif2: "Certification campaign :",
ttes_les_demandes: "All applications (over a maximum period of 2 months)",
ttes_les_hab: "All clearances",
dateCampagne: "Date of the certification campaign",
nomCampagne: "Name of certification campaign",
nomCL: "Name of local cell",
bilandroits: "Review of the recertification campaign",
droits: "of the rights",
achevement: "Completion %",
infoPersonnes: "Information on people",
beneficiaries: "Beneficiaries",
certificateurs: "Certificants",
infoRessources: "Information on resources",
assets: "Assets",
droit: "Rights",
globalResults: "Global Results",
participation: "Participation",
habilitationsCertifiees: "Certified Access",
habilitationsApprouvees: "Approved Access",
habilitationsRejetees: "Rejected Access",
habilitationsNonRevues: "non-reviewed Access",
participationPP: "participation by pole",
habilitationsRevuesPP: "Access reviewed by pole",
statisticsPerWeek: "Statistics % per week",
achevementParCL: "Completion by local cell",
week: "Week",
code_ap: "AP code",
code_unique_pm_du_droit: "BR'code of a right",
libelle_pm_du_droit: "BR'name of a right",
liste_droit_pm: "Rights list of a BR",
poleBilan: "of all poles (deployment/central cell)",
tasks: "Implementation tasks",
tasks_report: "Tasks reports",
description: "Description",
priorite: "Priority",
date_de_signature: "Date of signature",
id_tache: "Task ID",
date_action_implementeur: "Action decision date",
perimetre: "scope of execution",
report_perimeter: "Scope of implementation report",
multichoix: "Multiple Choice",
obligatoire: "Mandatory",
valeurs_possibles: "Possible values",
type_perimetre: "Scope Type",
nombre_de_membres_associes: "Number of associated members",
droits_contenus_dans_profil_metier: "Rights Contained in the Business Profile",
code_de_l_appli: "App code",
code_du_droit: "Right code",
responsable_de_l_uo: "Head of the OU",
nombre_de_membres: "Number of members",
statut_utilisateur: "User status",
sensibilite_du_droit: "Right sensibility",
convergence: "Convergence recertification CIB ITG",
convergence_application: "Application report",
convergence_application_entitlements: "Application entitlements report",
convergence_user_entitlements: "User entitlements report - convergence",
convergence_user_entitlements_name: "User entitlements (convergence)",
convergence_user_and_manager: "User and manager report",
inaccessible: "You are not allowed to access this section.",
ApplicationName: "ApplicationName",
ApplicatioName: "ApplicatioName",
ApplicationDescription: "ApplicationDescription",
ApplicationOwnerUID: "ApplicationOwnerUID",

EntitlementName: "EntitlementName",
EntitlementValue: "EntitlementValue",
EntitlementDisplayName: "EntitlementDisplayName",
EntitlementOwner: "EntitlementOwner",
EntitlementDescription: "EntitlementDescription",
ResourceName: "ResourceName",
Username: "Username",
UserDisplayName: "UserDisplayName",
UID: "UID",
AccountName: "AccountName",
Instance: "Instance",
EntitlementType: "EntitlementType",
username: "username",
userdisplayname: "userdisplayname",
firstname: "firstname",
lastname: "lastname",
usermanageruid: "usermanageruid",
Firstname: "Firstname",
Lastname: "Lastname",
Email: "Email",
ecartmyaccess: "Gap MyAccess - Base Habi",
manque_basehabi: "Missing rights in BaseHabi",
manque_myaccess: "Missing rights in MyAccess",
date_trait: "Process date",
rapp_ecart: "Gap report between MyAccess And BaseHabi",
filtreSOD: "SOD owned by the cell",
libelle_politique_sod: "SOD Policy Label",
libelle_regle: "Text of the rule",
gestionnaire_politique_sod: "SOD Policy Manager",
description_regle: "Rule description",
groupe_1_code_unique: "Group 1 unique code",
groupe_1_libelle_droit: "Group 1 text of the law",
groupe_2_code_unique: "Group 2 unique code",
groupe_2_libelle_droit: "Group 2 text of the law",
proprietaire_regle: "Rule owner",
group1sod: "The following right(s) ...",
group2sod: "... are in conflict with one or more of these rights",
btnshowmore: "Show more",
policy: "Policy",
rule: "Rule",
soddetail: "SOD details",
num1grpcodeunique: "Number of rights belonging to group 1",
num2grpcodeunique: "Number of rights belonging to group 2",
id_rule: "SOD Rule ID",
sod_count_by_metier: "Number of SOD by business line",
display_kpisod: "View SOD KPIs",
total_sod_count: "Total number of SOD rules",
closedisplay_kpisod: "Hide SOD KPIs",

beneficiary_uid: "Beneficiary UID",
beneficiary_display_name: "Beneficiary display name",
beneficiary_firstname: "Beneficiary firstname",
beneficiary_lastname: "Beneficiary lastname",
beneficiary_email: "Beneficiary email",
unit_manager_uid: "Unit manager UID",
unit_manager_display_name: "Unit manager display name",
unit_manager_firstname: "Unit manager firstname",
unit_manager_lastname: "Unit manager lastname",
unit_manager_email: "Unit manager email",
certifier_uid: "Certifier UID",
certifier_display_name: "Certifier display name",
certifier_firstname: "Certifier firstname",
certifier_lastname: "Certifier lastname",
certifier_email: "Certifier email",
right_display_name: "Right display name",
source: "Source",
all_perimeter: "All perimeters",
exclusion_pm: "Exclude Business Profile",
code_iso: "ISO Code",
code_iso_beneficiaire: "Beneficiary ISO Code"

}

public static fr_to_en: any = {
"Actif": "Active",
"Inactif": "Not active",
"Propriétaire du droit": "Right owner",
"Equipe Secu": "Security Team",
"Equipe": "Team",
"Manuel": "Manual",
"Automatique": "Automatic",
"Sensible": "Sensitive",
"Non Sensible": "Not sensitive",
"Equipe Sécurité": "Security Team",
"Equipe Generique": "Classic team",
"Cellule Locale": "Local Cell"
}

public static get() {
if (navigator.language.startsWith('fr')) {
  return this.fr;
} else {
  return this.en;
}
}

public static check_fr_to_en(text: any) {
if (navigator.language.startsWith('fr') || !this.fr_to_en.hasOwnProperty(text) || text == null || text.length < 1) {
  return text
} else {
  return this.fr_to_en[text]
}
}

public static check_fr_to_en_obj(obj: any) {
if (navigator.language.startsWith('fr')) {
  return obj
}
for (let i = 0; i < obj.length; i++) {
  Object.keys(obj[i]).forEach((e: any) => {
    obj[i][e] = this.check_fr_to_en(obj[i][e])
  })
}
return obj
}

}














  